CREATE TABLE KH_STUDENT (
STD_NO NUMBER PRIMARY KEY,
STD_NAME NVARCHAR2(5) NOT NULL,
STD_AGE NUMBER NOT NULL,
MAJOR NVARCHAR2(10) NOT NULL,
ENT_DATE DATE DEFAULT SYSDATE);

CREATE SEQUENCE SEQ_USER_NO1 NOCACHE;
DROP SEQUENCE SEQ_USER_NO1;
CREATE SEQUENCE SEQ_STU_NO NOCACHE;
ALTER SEQUENCE SEQ_STU_NO RENAME TO SEQ_STU_NO1; --이름변경안된대

INSERT INTO KH_STUDENT 
VALUES(SEQ_STU_NO.NEXTVAL, '김짱구', 20, '국어국문', DEFAULT );
INSERT INTO KH_STUDENT 
VALUES(SEQ_STU_NO.NEXTVAL, '김철수', 22, '영어영문', DEFAULT );
INSERT INTO KH_STUDENT 
VALUES(SEQ_STU_NO.NEXTVAL, '황맹구', 21, '수학', DEFAULT );

UPDATE KH_STUDENT
SET STD_NAME='남철수'
WHERE STD_NAME='김철수';

SELECT * FROM KH_STUDENT;

COMMIT;

SELECT STD_NO, STD_NAME, STD_AGE, MAJOR, TO_CHAR(ENT_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM KH_STUDENT;